OIDBMVCWEBSITE/Areas/Webmaster/Controllers/ComponentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OIDBMVCWEBSITE.Models;

namespace OIDBMVCWEBSITE.Areas.Webmaster.Controllers
{
    public class ComponentController : Controller
    {
        private OIDBEntities db = new OIDBEntities();

        // GET: /Webmaster/Component/
        public ActionResult Index()
        {
            var st_components = db.st_components.Include(s => s.st_module).Where(s => s.status == "Active").OrderBy(s => s.comp_type).ThenBy(s=>s.comp_name);
            return View(st_components.ToList());
        }

        // GET: /Webmaster/Component/Create
         [HttpPost]
         
        public ActionResult Create(int id = 0)
        {
            if (id == 0)
            {
                ViewBag.mod_id = new SelectList(db.st_module.Where(s => s.status == "Active").OrderBy(s => s.module_name), "mod_id", "module_name");
                return PartialView("Create");
            }
            else
            {
                st_components st_components = db.st_components.Find(id);
                ViewBag.mod_id1 = new SelectList(db.st_module.Where(s => s.status == "Active").OrderBy(s => s.module_name), "mod_id", "module_name", st_components.mod_id);
                if (st_components == null)
                {
                    return HttpNotFound();
                }
                return PartialView("Create",st_components);
            }


        }

        // POST: /Webmaster/Component/Create


        [HttpPost]
        // [ValidateAntiForgeryToken]
        public ActionResult Create1(st_components st_components1)
        {
            bool status = false;
            string msg = "Wrong Data Entry";
            if (ModelState.IsValid)
            {
                if (st_components1.comp_id == 0)
                {
                    st_module stm = db.st_module.Find(st_components1.mod_id);
                    st_components1.mod_id = st_components1.mod_id;
                    st_components1.comp_name = st_components1.comp_name;
                    st_components1.status = "Active";
                    st_components1.add_del = st_components1.add_del;
                    st_components1.comp_file = st_components1.comp_file;
                    st_components1.comp_type = stm.module_name;
                    st_components1.entry_by = 0;
                    st_components1.entry_date = Convert.ToDateTime(DateTime.Now.ToString("yyyy/MM/dd"));
                    st_components1.ip_addr = HttpContext.Request.UserHostAddress;
                    st_components1.flag = 0;
                    st_components1.pos = 0;
                    db.st_components.Add(st_components1);
                    int i = db.SaveChanges();
                    if (i > 0)
                    {
                        status = true;
                        msg = "Component Save Successfully";
                        // return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        status = false;
                        msg = "Record Not Saved";
                        // return Json(new { success = false, message = "Record Not Saved" }, JsonRequestBehavior.AllowGet);
                    }
                }
                else
                {
                    st_module stm = db.st_module.Find(st_components1.mod_id);
                    st_components1.mod_id = st_components1.mod_id;
                    st_components1.comp_name = st_components1.comp_name;
                    st_components1.status = "Active";
                    st_components1.add_del = st_components1.add_del;
                    st_components1.comp_file = st_components1.comp_file;
                    st_components1.comp_type = stm.module_name;
                    st_components1.entry_by = 0;
                    st_components1.entry_date = Convert.ToDateTime(DateTime.Now.ToString("yyyy/MM/dd"));
                    st_components1.ip_addr = HttpContext.Request.UserHostAddress;
                    st_components1.flag = 0;
                    st_components1.pos = 0;
                    db.Entry(st_components1).State = EntityState.Modified;
                    int i = db.SaveChanges();
                    if (i > 0)
                    {
                        status = true;
                        msg = "Component Updated Successfully";
                    }
                    else
                    {
                        status = false;
                        msg = "Record Not Updated";
                    }
                }
            }
            if (Request.IsAjaxRequest())
            {
                return Json(new { success = status, message = msg }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                ViewBag.mod_id = new SelectList(db.st_module.Where(s => s.status == "Active").OrderBy(s => s.module_name), "mod_id", "module_name");
                return View(st_components1);
            }


        }

        // POST: /Webmaster/Component/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bool status = false;
            st_components st_components = db.st_components.Find(id);
            if (st_components != null)
            {
                st_components.status = "Deleted";
                db.SaveChanges();
                status = true;
            }
            return Json(new { success = status, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

OIDBMVCWEBSITE/Areas/Webmaster/Views/Component/Create.cshtml
@model OIDBMVCWEBSITE.Models.st_components
@{
    Layout = null;
}
<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header modal-header-danger">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Add / Edit Component</h4>
        </div>
        @using (Html.BeginForm("Create1", "Component", FormMethod.Post, new { onsubmit = "return SubmitForm1(this)" }))
        {
            if (Model != null && Model.comp_id > 0)
            {
                @Html.HiddenFor(model => model.comp_id)
            }
            <div class="modal-body">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.mod_id)
                            @Html.DropDownListFor(model => model.mod_id, ViewBag.mod_id1 as SelectList, "--Select--", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.mod_id, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.comp_name)
                            @Html.TextBoxFor(model => model.comp_name, new { @class = "form-control", @placeholder = "Component Name" })
                            @Html.ValidationMessageFor(model => model.comp_name, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.add_del)
                            @Html.RadioButtonFor(model => model.add_del, "Yes", new { id = "Yes" }) Yes
                            @Html.RadioButtonFor(model => model.add_del, "No", new { id = "No" }) No
                            @Html.ValidationMessageFor(model => model.add_del, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-group">
                            @Html.LabelFor(model => model.comp_file)
                            @Html.TextBoxFor(model => model.comp_file, new { @class = "form-control", @placeholder = "File Name" })
                            @Html.ValidationMessageFor(model => model.comp_file, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                @if (Model != null && Model.comp_id > 0)
                {
                <input type="submit" value="Update" class="btn btn-success" id="btnSubmit" />
                }
                else
                {<input type="submit" value="Create" class="btn btn-success" id="btnSubmit" />}
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        }
    </div>
</div>

OIDBMVCWEBSITE/Areas/Webmaster/Views/Component/Index.cshtml
@model IEnumerable<OIDBMVCWEBSITE.Models.st_components>

@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Webmaster/Views/Shared/_Layout.cshtml";
}
<style type="text/css">
    .GroupHeaderStyle {
        border: solid 0px Black;
        background-color: #4682B4;
        color: #ffffff;
        font-weight: bold;
        text-align: center;
    }
</style>
<div class="row">
    <div class="col-lg-12">
        <div class="page-header">
            <a id="AddComponent" data-id="0" class="btn btn-success AddComponentclass">Add New Component</a>
            @*<a id="AddComponent" onclick="AddEditEmployee(0)" class="btn btn-success">Add New Component</a>*@
        </div>
    </div>
</div>

<div id='myModal' class='modal fade in'>
    <div id='myModalContent'></div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title "><i class="fa fa-user"></i> Components Details</h3>
            </div>
            <div class="panel-body">
                <div class="row">

                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>
                                        Sr.No.
                                    </th>
                                    <th>
                                      Module Name
                                    </th>
                                    <th>
                                       Component Name
                                    </th>

                                    <th>
                                        Add/Edit/Delete Option
                                    </th>
                                    <th>
                                        Component File
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @{int sr = 1; }
                                @foreach (var item1 in Model.GroupBy(x => x.comp_type))
                                {

                                    <tr>
                                        <td colspan="6" class="GroupHeaderStyle">
                                            Component Type :  @item1.Key
                                        </td>
                                    </tr>
                                    foreach (var item in item1)
                                    {

                                        <tr>
                                            <td>
                                                @(sr++).
                                            </td>
                                            <td>

                                                @Html.DisplayFor(modelItem => item.st_module.module_name)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.comp_name)
                                            </td>

                                            <td>
                                                @Html.DisplayFor(modelItem => item.add_del)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.comp_file)
                                            </td>
                                            <td>
                                                <a href="#" id="EditComponent" data-id="@item.comp_id" class="AddComponentclass" ><i class="fa fa-edit fa-2x text-success"></i></a>
                                                <a href="#" id="DeleteanchorComp" data-id="@item.comp_id" ><i class="fa fa-trash fa-2x text-success"></i></a>
                                              
                                            </td>
                                        </tr>
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
 